services:
  - type: web
    name: linprosolv
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir ban0406 app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"
